spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      properties:
        "[spring.json.value.default.type]": "edu.miu.sa.reservation.entity.Account"
        "[spring.json.trusted.packages]": ["edu.miu.sa.reservation"]
    producer:
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      properties:
        "[spring.json.add.type.headers]": false
  data:
    mongodb:
      host: "localhost"
      port: "27017"
      database: "accounts"
kafka:
  topic: "topic1"