spring:
  kafka:
    consumer:
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      properties:
        "[spring.json.value.default.type]": "edu.miu.sa.reservation.entity.Account"
        "[spring.json.trusted.packages]": "edu.miu.sa.reservation"
    producer:
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      properties:
        "[spring.json.add.type.headers]": false

---
spring:
  config:
    activate:
      on-profile: dev
  kafka:
    bootstrap-servers: "localhost:9092"
  data:
    cassandra:
      port: 9042
      contact-points: account-db
      keyspace-name: account
      schema-action: create_if_not_exists
      entity-base-package: edu.miu.sa.reservation.entity
  zipkin:
    service:
      name: "account-service"
kafka:
  topic:
    get: "GetAccountEvent"
    response: "ResponseGetAccountEvent"
    created: "AccountCreatedEvent"
jwt:
  secret: "top_secret"
---
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
  main:
    allow-bean-definition-overriding: ${SPRING_ALLOW_BEAN_DEFINITION_OVERRIDING}
  data:
    cassandra:
      contact-points: ${DB_CONTACT_POINTS}
      port: ${DB_PORT}
      keyspace-name: ${DB_ACCOUNT_KEYSPACE}
      schema-action: ${DB_SCHEME_ACTION}
      local-datacenter: ${DB_DATACENTER}
      request:
        timeout: ${DB_REQUEST_TIMEOUT}
  zipkin:
    baseUrl: ${ZIPKIN_SERVER}
    service:
      name: ${ZIPKIN_ACCOUNT_SERVICE}
kafka:
  topic:
    get: ${ACCOUNT_REQUEST_TOPIC}
    response: ${ACCOUNT_GET_TOPIC}
    created: ${ACCOUNT_CREATED_TOPIC}
server:
  port: ${SERVICE_PORT}

jwt:
  secret: ${JWT_SECRET}