spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
#      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      properties:
        "[spring.json.value.default.type]": "edu.miu.sa.account.entity.Account"
        "[spring.json.trusted.packages]": ["edu.miu.sa.account"]
    producer:
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      properties:
        "[spring.json.add.type.headers]": false
  data:
    cassandra:
      port: 9042
      contact-points: account-db
      keyspace-name: account_ks
      schema-action: create_if_not_exists
      entity-base-package: edu.miu.sa.account.entity
kafka:
  topic:
    get: "GET_ACCOUNT_EVENT"
    response: "RESPONSE_GET_ACCOUNT_EVENT"
    created: "ACCOUNT_CREATED_EVENT"